LOAD_EXISTING_MODEL = False

SAVE_MODEL = False

# Callbacks
LR_SCHEDULER_ENABLED = True
CHECKPOINT_BEST_LOSS_ENABLED = False
CHECKPOINT_BEST_ACC_ENABLED = True
CHECKPOINT_LATEST_ENABLED = False
SAVE_TRAIN_STATS_ENABLED = False
PLOT_RESULTS_ENABLED = True

EARLY_STOPPING_ENABLED = False
